/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajojoseluis;

import com.mysql.jdbc.CommunicationsException;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import misclases.Conex;

/**
 *
 * @author code
 */
public class AgregarReparacion extends javax.swing.JFrame {

    DefaultComboBoxModel<String> modelMec = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> modelCoch = new DefaultComboBoxModel<>();
    ArrayList<String> dniMec = new ArrayList<>();
    ArrayList<String> nBas = new ArrayList<>();

    public void AgregarMec() {
        try {
            Connection conexion = Conex.devolverConex();
            PreparedStatement sentencia = (PreparedStatement) conexion.prepareStatement("select dni, nombre from mecanicos");
            ResultSet rs = sentencia.executeQuery();
            while (rs.next()) {
                String nombre = rs.getString("nombre");
                modelMec.addElement(nombre);
                dniMec.add(rs.getString("dni"));
            }
            rs.close();
            sentencia.close();
            Conex.CerrarConex();
        } catch (CommunicationsException e) {
            JOptionPane.showMessageDialog(this, "La base de datos no esta encendida");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            ;
        }
    }

    public void AgregarCoches() {
        try {
            Connection conexion = Conex.devolverConex();
            PreparedStatement sentencia = (PreparedStatement) conexion.prepareStatement("select n_bastidor, marca,modelo from coches");
            ResultSet rs = sentencia.executeQuery();
            while (rs.next()) {
                String modelo = rs.getString("modelo");
                String marca = rs.getString("marca");

                modelCoch.addElement(marca + " " + modelo);
                nBas.add(rs.getString("n_bastidor"));
            }
            rs.close();
            sentencia.close();
            Conex.CerrarConex();
        } catch (CommunicationsException e) {
            JOptionPane.showMessageDialog(this, "La base de datos no esta encendida");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            ;
        }
    }

    /**
     * Creates new form AgregarReparacion
     */
    public AgregarReparacion() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Formulario de agregar");
        this.setSize(720, 800);
        cmbCoch.setModel(modelCoch);
        cmbMec.setModel(modelMec);
        modelCoch.removeAllElements();
        modelMec.removeAllElements();
        AgregarCoches();
        AgregarMec();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbMec = new javax.swing.JComboBox<>();
        cmbCoch = new javax.swing.JComboBox<>();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        txtBas = new javax.swing.JTextField();
        btnInicio = new javax.swing.JButton();
        btnFin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fechaFin = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fechaIni = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(60, 60, 60));
        jPanel3.setForeground(new java.awt.Color(20, 20, 20));

        titulo.setFont(new java.awt.Font("Gill Sans MT", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(204, 51, 255));
        titulo.setText("Agregar Reparación");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(titulo)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titulo)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 120));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(200, 200, 200));
        jLabel3.setText("Descripcion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(200, 200, 200));
        jLabel4.setText("Coche");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(200, 200, 200));
        jLabel5.setText("NºReparación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(200, 200, 200));
        jLabel2.setText("Mecanico");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        cmbMec.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        cmbMec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        cmbCoch.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        cmbCoch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbCoch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));
        getContentPane().add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 380, 240));

        txtBas.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        getContentPane().add(txtBas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 160, -1));

        btnInicio.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btnInicio.setText("Agregar Fecha Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        btnFin.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btnFin.setText("Agregar Fecha Fin");
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });
        getContentPane().add(btnFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(200, 200, 200));
        jLabel6.setText("Fecha fin:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, -1, -1));

        fechaFin.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        fechaFin.setForeground(new java.awt.Color(200, 200, 200));
        fechaFin.setText("2024-05-13");
        getContentPane().add(fechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(200, 200, 200));
        jLabel10.setText("Fecha inicio:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        fechaIni.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        fechaIni.setForeground(new java.awt.Color(200, 200, 200));
        fechaIni.setText("2024-05-12");
        getContentPane().add(fechaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btnAgregar.setText("Agregar Reparación");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 660, 230, 70));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 190, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIX/morado.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 720, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        SimpleDateFormat ff = new SimpleDateFormat("yyyy-MM-dd");
        String fecha = ff.format(jCalendar1.getCalendar().getTime());
        fechaIni.setText(fecha);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        SimpleDateFormat ff = new SimpleDateFormat("yyyy-MM-dd");
        String fecha = ff.format(jCalendar1.getCalendar().getTime());
        fechaFin.setText(fecha);
    }//GEN-LAST:event_btnFinActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        if (Comprobaciones()) {
            try {
                Connection conexion = Conex.devolverConex();
                String sql = "insert into reparaciones values (?, ?, ?, ?, ?,? )";
                PreparedStatement sentencia = (PreparedStatement) conexion.prepareStatement(sql);
                sentencia.setString(1, dniMec.get(cmbMec.getSelectedIndex()));
                sentencia.setString(2, nBas.get(cmbCoch.getSelectedIndex()));
                sentencia.setInt(3, Integer.parseInt(txtBas.getText()));
                sentencia.setString(4, fechaIni.getText());
                sentencia.setString(5, jTextArea2.getText());
                sentencia.setString(6,fechaFin.getText());
                sentencia.executeUpdate();
                JOptionPane.showMessageDialog(this, "Se ha realizado la inserción");
                sentencia.close();
                Conex.CerrarConex();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarReparacion().setVisible(true);
            }
        });
    }

    public boolean Comprobaciones() {
        if (fechaIni.getText().compareTo(fechaFin.getText()) == 1) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio es mayor a la de inicio");
            return false;
        }
        try {
            Connection conexion = Conex.devolverConex();
            PreparedStatement sentencia = (PreparedStatement) conexion.prepareStatement("select n_reparacion from reparaciones");
            ResultSet rs = sentencia.executeQuery();
            while (rs.next()) {
                String n = rs.getString("n_reparacion");
                if ((n.equals(txtBas.getText())) || (txtBas.getText().isEmpty())) {
                    JOptionPane.showMessageDialog(this, "El numero de reparacion ya esta usado o esta vacio");
                    return false;
                }
            }
            rs.close();
            sentencia.close();
            Conex.CerrarConex();
        } catch (CommunicationsException e) {
            JOptionPane.showMessageDialog(this, "La base de datos no esta encendida");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            ;
        }
        if (jTextArea2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La descripcion no puede estar vacia");
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnFin;
    private javax.swing.JButton btnInicio;
    private javax.swing.JComboBox<String> cmbCoch;
    private javax.swing.JComboBox<String> cmbMec;
    private javax.swing.JLabel fechaFin;
    private javax.swing.JLabel fechaIni;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtBas;
    // End of variables declaration//GEN-END:variables
}
