/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajojoseluis;

import com.mysql.jdbc.CommunicationsException;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import misclases.Conex;
import misclases.Validador;

/**
 *
 * @author code
 */
public class AgregarCoche extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCoche
     */
    DefaultComboBoxModel<String> model1 = new DefaultComboBoxModel<>();
    ArrayList<String> dni = new ArrayList<>();
    int seleccion;
    JFileChooser fc;
    String fecha;
    File origen;
    ArrayList<String> extensiones = new ArrayList<>();      
    
    

    public AgregarCoche() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Agregar coches");
        this.setSize(912, 580);
        dni_proveedor.setModel(model1);
        model1.removeAllElements();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        AgregarPro();
        extensiones.add("jpg");
        extensiones.add("jgeg");
        extensiones.add("png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        n_bastidor = new javax.swing.JTextField();
        km = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        cv = new javax.swing.JTextField();
        estado = new javax.swing.JComboBox<>();
        categoria = new javax.swing.JComboBox<>();
        dni_proveedor = new javax.swing.JComboBox<>();
        imagen = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        btnAgregar = new javax.swing.JButton();
        txtImagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agregar coche");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero de bastidor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, 20));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Km:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 50, -1));

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cv:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categoria:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 100, -1));

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Marca:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Modelo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Dni_proveedor:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Imagen");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 70, -1));

        n_bastidor.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        getContentPane().add(n_bastidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 190, -1));

        km.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        getContentPane().add(km, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 80, -1));

        marca.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        getContentPane().add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 90, -1));

        precio.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 80, -1));

        modelo.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        getContentPane().add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 130, -1));

        cv.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        getContentPane().add(cv, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 80, -1));

        estado.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Usado", "Reparado", "km0", "Siniestrado" }));
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        categoria.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ranchera", "sedan", "coupe", "berlina", "superdeportivo", "todoterreno", "hatchback", "hothatch" }));
        getContentPane().add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        dni_proveedor.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        dni_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dni_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dni_proveedorActionPerformed(evt);
            }
        });
        getContentPane().add(dni_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        imagen.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        imagen.setText("Añadir Imagen");
        imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenActionPerformed(evt);
            }
        });
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));
        getContentPane().add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 370, 220));

        btnAgregar.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 51, 51));
        btnAgregar.setText("Agregar coche");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 190, 50));

        txtImagen.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        txtImagen.setForeground(new java.awt.Color(187, 187, 188));
        getContentPane().add(txtImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIX/lambo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dni_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dni_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dni_proveedorActionPerformed

    private void imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenActionPerformed
        fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagenes", "jpg", "jpeg", "png");
        fc.setFileFilter(filter);
        seleccion = fc.showOpenDialog(this);


    }//GEN-LAST:event_imagenActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (Comprobaciones()) {
            try {
                Connection conexion = (Connection) Conex.devolverConex(AgregarCoche.this);
                String sql = "insert into coches values (? , ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement sentecia = (PreparedStatement) conexion.prepareStatement(sql);
                AgregarSentencia(sentecia);
                sentecia.executeUpdate();
                JOptionPane.showMessageDialog(this, "Se ha realizado la inserción");
                sentecia.close();
                Conex.CerrarConex();
                dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void AgregarPro() {

        try {
            Connection conexion = (Connection) Conex.devolverConex(AgregarCoche.this);
            PreparedStatement sentecia = (PreparedStatement) conexion.prepareStatement("select dni, nombre from proveedores");
            ResultSet rs = sentecia.executeQuery();
            while (rs.next()) {
                String nombre = rs.getString("nombre");
                model1.addElement(nombre);
                dni.add(rs.getString("dni"));
            }
            rs.close();
            sentecia.close();
            Conex.CerrarConex();
        } catch (CommunicationsException e) {
            JOptionPane.showMessageDialog(this, "La base de datos no esta encendida");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            ;
        }
    }

    public void copiarArchivo(File origen, File destino) {
        try (FileInputStream fis = new FileInputStream(origen); FileOutputStream fos = new FileOutputStream(destino)) {

            byte[] buffer = new byte[1024];
            int longitud;

            while ((longitud = fis.read(buffer)) > 0) {
                fos.write(buffer, 0, longitud);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(AgregarCoche.this, e);
        }
    }

    public boolean Comprobaciones() {
        try {
            if (Validador.validarN_bastidor(n_bastidor.getText(), this)) {
                if (Integer.parseInt(km.getText()) >= 0) {
                    if (Integer.parseInt(cv.getText()) > 0) {
                        if (!modelo.getText().isEmpty() || !marca.getText().isEmpty()) {
                            if (Integer.parseInt(precio.getText()) > 1000) {
                                SimpleDateFormat ff = new SimpleDateFormat("yyyy-MM-dd");
                                fecha = ff.format(jCalendar1.getCalendar().getTime());
                                if (seleccion == JFileChooser.APPROVE_OPTION) {

                                    origen = fc.getSelectedFile();
                                    String extension = getExtension(origen);
                                    if (extensiones.contains(extension.toLowerCase())) {
                                        txtImagen.setText(origen.getName());
                                        txtImagen.setText(origen.getName());
                                        String currentDirectory = System.getProperty("user.dir");
                                    File destinoDir = new File(System.getProperty("user.dir")+"\\src\\img\\coches");
                                    File destino = new File(destinoDir, origen.getName());
                                        System.out.println(origen);
                                        System.out.println(destino);
                                    copiarArchivo(origen, destino);
                                    return true;
                                    } else {
                                        JOptionPane.showMessageDialog(this, "El archivo seleccionado no es una imagen válida.");
                                        txtImagen.setText("");
                                    }
                                    
                                } else {
                                    JOptionPane.showMessageDialog(this, "Foto no seleccionada");

                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "El precio esta mal");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "El modelo y o la marca estan vacios");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Los cv estan mal");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Los km estan mal");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "No se puede poner texto en los inputs que esperan numero");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);

        }
        return false;

    }

    public String getExtension(File file) {
        String name = file.getName();
        int lastIndex = name.lastIndexOf('.');
        if (lastIndex > 0 && lastIndex < name.length() - 1) {
            return name.substring(lastIndex + 1);
        } else {
            return "";
        }
    }

    public void AgregarSentencia(PreparedStatement sentecia) {
        try {
            sentecia.setString(1, n_bastidor.getText());
            sentecia.setInt(2, Integer.parseInt(precio.getText()));
            sentecia.setString(3, (String) estado.getSelectedItem());
            sentecia.setInt(4, Integer.parseInt(km.getText()));
            sentecia.setInt(5, Integer.parseInt(cv.getText()));
            sentecia.setString(6, (String) categoria.getSelectedItem());
            sentecia.setString(7, marca.getText());
            sentecia.setString(8, modelo.getText());
            sentecia.setString(9, dni.get(dni_proveedor.getSelectedIndex()));
            sentecia.setString(10, fecha);
            sentecia.setString(11, origen.getName());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCoche().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JTextField cv;
    private javax.swing.JComboBox<String> dni_proveedor;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JButton imagen;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField km;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField n_bastidor;
    private javax.swing.JTextField precio;
    private javax.swing.JLabel txtImagen;
    // End of variables declaration//GEN-END:variables
}
