package trabajojoseluis;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import misclases.Conex;
import static misclases.Encriptador.encryptPassword;
import misclases.Validador;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author code
 */
public class Agregar extends javax.swing.JFrame {

    String usuario;

    /**
     * Creates new form Agregar
     */
    public Agregar(String rb) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Formulario de agregar");
        this.setSize(615, 640);
        titulo.setText("Agregar " + rb);
        usuario = rb;
        if (usuario.equals("clientes") || usuario.equals("proveedores")) {
            Agregar.this.remove(txtSueldo);
            Agregar.this.remove(sueldo);
        }
        if (!usuario.equals("vendedores")) {
            Agregar.this.remove(contraseña);
            Agregar.this.remove(txtpasswd);

        }
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sueldo = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        txtpasswd = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel1.setText("DNI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel3.setText("Numero");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        contraseña.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        contraseña.setText("Contraseña");
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        sueldo.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        sueldo.setText("Sueldo");
        getContentPane().add(sueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        txtnombre.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(255, 51, 51));
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreKeyPressed(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, -1));

        txtdni.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        txtdni.setForeground(new java.awt.Color(255, 51, 51));
        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdniKeyPressed(evt);
            }
        });
        getContentPane().add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 150, -1));

        txtSueldo.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        txtSueldo.setForeground(new java.awt.Color(255, 51, 51));
        txtSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSueldoKeyPressed(evt);
            }
        });
        getContentPane().add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 90, -1));

        txtemail.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        txtemail.setForeground(new java.awt.Color(255, 51, 51));
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 280, -1));

        txtnum.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        txtnum.setForeground(new java.awt.Color(255, 51, 51));
        txtnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumKeyPressed(evt);
            }
        });
        getContentPane().add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 100, -1));

        btnAgregar.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 51, 51));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 290, 110));

        jPanel3.setBackground(new java.awt.Color(60, 60, 60));
        jPanel3.setForeground(new java.awt.Color(20, 20, 20));

        titulo.setFont(new java.awt.Font("Gill Sans MT", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 51, 51));
        titulo.setText("titulo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(titulo)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(titulo)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 140));

        txtpasswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswdKeyPressed(evt);
            }
        });
        getContentPane().add(txtpasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 170, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIX/gris.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 620, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (Validador.validarEmail(txtemail.getText(), Agregar.this)) {
            if (Validador.validarDNI(txtdni.getText(), Agregar.this)) {
                if (Validador.validarNumero(Integer.parseInt(txtnum.getText()), this)) {
                    if (usuario.equals("clientes") || usuario.equals("proveedores")) {

                        try {
                            Connection conexion = Conex.devolverConex();

                            String sql = "insert into " + usuario + " values (?,?,?,?);";

                            PreparedStatement sentecia = (PreparedStatement) conexion.prepareStatement(sql);

                            sentecia.setString(1, txtdni.getText());
                            sentecia.setString(2, txtnombre.getText());
                            sentecia.setInt(3, Integer.parseInt(txtnum.getText()));
                            sentecia.setString(4, txtemail.getText());

                            System.out.println(sentecia);

                            sentecia.executeUpdate();
                            sentecia.close();
                            Conex.CerrarConex();
                            JOptionPane.showMessageDialog(Agregar.this, "Agregado correctamente");
                            dispose();

                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(Agregar.this, e);
                        }

                    } else if (usuario.equals("vendedores")) {
                        if (Validador.validarSueldo(Integer.parseInt(txtSueldo.getText()), this)) {
                            try {
                                Connection conexion = Conex.devolverConex();

                                String sql = "insert into " + usuario + " values ( ? , ? , ? , ? , ? , ?,0 );";

                                PreparedStatement sentecia = (PreparedStatement) conexion.prepareStatement(sql);

                                sentecia.setString(1, txtdni.getText());
                                sentecia.setString(2, txtnombre.getText());
                                sentecia.setInt(3, Integer.parseInt(txtnum.getText()));
                                sentecia.setString(4, txtemail.getText());
                                sentecia.setInt(5, Integer.parseInt(txtSueldo.getText()));
                                sentecia.setString(6, encryptPassword(txtpasswd.getText()));

                                sentecia.executeUpdate();
                                sentecia.close();
                                Conex.CerrarConex();
                                JOptionPane.showMessageDialog(Agregar.this, "Agregado correctamente");
                                dispose();

                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(Agregar.this, e);
                            }
                        }
                    } else {
                        {
                            if (Validador.validarSueldo(Integer.parseInt(txtSueldo.getText()), this)) {
                                try {
                                    Connection conexion = Conex.devolverConex();

                                    String sql = "insert into " + usuario + " values ( ? , ? , ? , ? , ?  );";

                                    PreparedStatement sentecia = (PreparedStatement) conexion.prepareStatement(sql);

                                    sentecia.setString(1, txtdni.getText());
                                    sentecia.setString(2, txtnombre.getText());
                                    sentecia.setInt(3, Integer.parseInt(txtnum.getText()));
                                    sentecia.setString(4, txtemail.getText());
                                    sentecia.setInt(5, Integer.parseInt(txtSueldo.getText()));

                                    sentecia.executeUpdate();
                                    sentecia.close();
                                    Conex.CerrarConex();
                                    JOptionPane.showMessageDialog(Agregar.this, "Agregado correctamente");
                                    dispose();

                                } catch (Exception e) {
                                    JOptionPane.showMessageDialog(Agregar.this, e);
                                }
                            }
                        }
                    }

                }

            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtdni.requestFocus();
        }
    }//GEN-LAST:event_txtnombreKeyPressed

    private void txtdniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtnum.requestFocus();
        }
    }//GEN-LAST:event_txtdniKeyPressed

    private void txtnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtemail.requestFocus();
        }
    }//GEN-LAST:event_txtnumKeyPressed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        if (usuario.equals("clientes") || usuario.equals("proveedores")) {
            if (evt.getKeyCode() == evt.VK_ENTER) {
                txtpasswd.requestFocus();
            }
        } else {
            if (evt.getKeyCode() == evt.VK_ENTER) {
                txtSueldo.requestFocus();
            }

        }
    }//GEN-LAST:event_txtemailKeyPressed

    private void txtSueldoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtpasswd.requestFocus();
        }
    }//GEN-LAST:event_txtSueldoKeyPressed

    private void txtpasswdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswdKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            btnAgregar.requestFocus();
        }
    }//GEN-LAST:event_txtpasswdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel sueldo;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnum;
    private javax.swing.JPasswordField txtpasswd;
    // End of variables declaration//GEN-END:variables
}
