/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajojoseluis;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author code
 */
public class Coches extends javax.swing.JFrame {

    /**
     * Creates new form Coches
     */
   
    public Coches() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Gestion de coches");
        this.setSize(1000, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rbTodos = new javax.swing.JRadioButton();
        rbDisp = new javax.swing.JRadioButton();
        rpVendidos = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        modelo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        marca = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        cv = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        km = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coches/e55.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 590, 380));

        jComboBox1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Listado de coches");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        buttonGroup1.add(rbTodos);
        rbTodos.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        rbTodos.setForeground(new java.awt.Color(255, 0, 51));
        rbTodos.setText("Todos");
        getContentPane().add(rbTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        buttonGroup1.add(rbDisp);
        rbDisp.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        rbDisp.setForeground(new java.awt.Color(255, 0, 51));
        rbDisp.setText("Disponibles");
        getContentPane().add(rbDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        buttonGroup1.add(rpVendidos);
        rpVendidos.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        rpVendidos.setForeground(new java.awt.Color(255, 0, 51));
        rpVendidos.setText("Vendidos");
        getContentPane().add(rpVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Coche:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Modelo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        modelo.setFont(new java.awt.Font("Gill Sans MT", 0, 22)); // NOI18N
        modelo.setForeground(new java.awt.Color(255, 0, 51));
        modelo.setText("jLabel5");
        getContentPane().add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Marca:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        marca.setFont(new java.awt.Font("Gill Sans MT", 0, 22)); // NOI18N
        marca.setForeground(new java.awt.Color(255, 0, 51));
        marca.setText("jLabel7");
        getContentPane().add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("Categoria:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        categoria.setFont(new java.awt.Font("Gill Sans MT", 0, 22)); // NOI18N
        categoria.setForeground(new java.awt.Color(255, 0, 51));
        categoria.setText("jLabel9");
        getContentPane().add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("KM:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        estado.setFont(new java.awt.Font("Gill Sans MT", 0, 22)); // NOI18N
        estado.setForeground(new java.awt.Color(255, 0, 51));
        estado.setText("jLabel11");
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, -1));

        cv.setFont(new java.awt.Font("Gill Sans MT", 0, 22)); // NOI18N
        cv.setForeground(new java.awt.Color(255, 0, 51));
        cv.setText("Estado:");
        getContentPane().add(cv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, -1, -1));

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("CV:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, -1, -1));

        jLabel14.setFont(new java.awt.Font("Gill Sans MT", 0, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("Estado:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        km.setFont(new java.awt.Font("Gill Sans MT", 0, 22)); // NOI18N
        km.setForeground(new java.awt.Color(255, 0, 51));
        km.setText("Estado:");
        getContentPane().add(km, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 1000)); // NOI18N
        jLabel7.setText("**");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 120));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIX/spa.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coches().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel cv;
    private javax.swing.JLabel estado;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel km;
    private javax.swing.JLabel marca;
    private javax.swing.JLabel modelo;
    private javax.swing.JRadioButton rbDisp;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JRadioButton rpVendidos;
    // End of variables declaration//GEN-END:variables
}
